name: Run CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: http://127.0.0.1:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.12.7'
          activate-environment: loan-approval-prediction
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Start MLflow tracking server
        shell: bash -l {0}
        run: |
          nohup mlflow server \
            --backend-store-uri file:./mlruns \
            --default-artifact-root ./mlruns \
            --host 127.0.0.1 \
            --port 5000 > mlflow.log 2>&1 &
          sleep 10

      - name: Run MLflow project
        shell: bash -l {0}
        run: |
          mlflow run MLProject

      - name: Get latest MLflow run_id
        run: |
          EXPERIMENT_ID=$(mlflow experiments list | grep 'Eksperimen Loan Approval Model' | awk '{print $1}')
          echo "Experiment ID: $EXPERIMENT_ID"

          RUN_ID=$(mlflow runs list -e $EXPERIMENT_ID --order-by start_time desc | awk 'NR==2 {print $1}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
